# Generated by Django 2.2.6 on 2020-07-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('СОБАКА', 'СОБАКА'), ('КОШКА', 'КОШКА'), ('ПОПУГАЙ', 'ПОПУГАЙ')], default='СОБАКА', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Кличка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('photo', models.ImageField(blank=True, upload_to='photo', verbose_name='Фото')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_shelter.Breed', verbose_name='Порода')),
                ('kind', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='p_shelter.Kind', verbose_name='Вид животного')),
            ],
        ),
    ]
